### ISSUE TITLE
Request for used slurm.utils

### ISSUE THREAD

**Issue by WilliamYi96** [universome/class-norm-for-czsl#2]
Hi @universome ,

In _nm-zsl/src/run.py_, line 11, you have:

`from slurm.utils import generate_experiments_from_hpo_grid`

However, for the currently released code, slurm.utils are not provided. Could you please also add this to the code?

Thanks a lot!

**Comment by universome** [comment]
Hi! I added the slurm utils to the repo. I am closing the issue for now, but if you'll face any other problems feel free to reopen it or create a new issue.
